### PR TITLE
[ADD] coinsamatik: add dependencies for stock_no_negative T#54677

### PR DESCRIPTION
**Pull request by slitheryduke11**

### CODE REVIEW

**Comment by slitheryduke11** [comment]
@hugho-ad This PR is ready for review.

**Comment by slitheryduke11** [comment]
@hugho-ad I updated the PR so that the commit you added to Gitlab is also reflected here.

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
@BruceSOT 

ready to review

**Comment by hugho-ad** [comment]
I just updated the submodule

**Comment by hugho-ad** [comment]
@BruceSOT 

did you test it at lest on odoosh?

the branch 13.0-add_stock_no_negative_submodule-hedguhar didn't change to staging state


could you please made the correct functional review pls?

**Comment by hugho-ad** [comment]
@BruceSOT 

Done

**Comment by BruceSOT** [comment]
Great ! Thank you @hugho-ad and @slitheryduke11 !

**Pull request merged**
